"""
╔═══════════════════════════════════════════════════════════════════════════════╗
║         STRESS TEST REPORTS - Report Generation                               ║
╚═══════════════════════════════════════════════════════════════════════════════╝

Generates human-readable reports from stress test results.
"""

import json
from dataclasses import dataclass
from typing import Dict, List, Optional
from datetime import datetime
from pathlib import Path
import logging

logger = logging.getLogger("StressTest.Reports")


@dataclass
class StressTestReport:
    """Stress test report."""
    title: str
    generated_at: datetime
    summary: Dict
    scenarios: List[Dict]
    recommendations: List[str]
    
    def to_markdown(self) -> str:
        """Generate markdown report."""
        lines = [
            f"# {self.title}",
            "",
            f"**Generated:** {self.generated_at.strftime('%Y-%m-%d %H:%M:%S')}",
            "",
            "---",
            "",
            "## Executive Summary",
            "",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Total Scenarios | {self.summary['total']} |",
            f"| Passed | {self.summary['passed']} |",
            f"| Failed | {self.summary['failed']} |",
            f"| Pass Rate | {self.summary['pass_rate']:.1%} |",
            f"| Duration | {self.summary['duration']:.1f}s |",
            "",
            "### Status: " + ("✅ **PASSED**" if self.summary['all_passed'] else "❌ **FAILED**"),
            "",
            "---",
            "",
            "## Scenario Results",
            "",
        ]
        
        for scenario in self.scenarios:
            status = "✅" if scenario['passed'] else "❌"
            lines.append(f"### {status} {scenario['name']}")
            lines.append("")
            lines.append(f"**Type:** {scenario['type']}")
            lines.append(f"**Duration:** {scenario.get('duration', 'N/A')}s")
            lines.append("")
            
            if scenario.get('halt_time_ms'):
                lines.append(f"- Halt Time: {scenario['halt_time_ms']:.1f}ms")
            if scenario.get('max_drawdown'):
                lines.append(f"- Max Drawdown: {scenario['max_drawdown']:.2f}%")
            
            if scenario.get('errors'):
                lines.append("")
                lines.append("**Errors:**")
                for error in scenario['errors']:
                    lines.append(f"- ⚠️ {error}")
            
            lines.append("")
        
        lines.extend([
            "---",
            "",
            "## Recommendations",
            "",
        ])
        
        for rec in self.recommendations:
            lines.append(f"- {rec}")
        
        lines.extend([
            "",
            "---",
            "",
            f"*Report generated by Stress Test Suite*",
        ])
        
        return "\n".join(lines)
    
    def to_html(self) -> str:
        """Generate HTML report."""
        # Simple HTML wrapper around markdown
        md = self.to_markdown()
        
        html = f"""<!DOCTYPE html>
<html>
<head>
    <title>{self.title}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
               max-width: 800px; margin: 0 auto; padding: 20px; }}
        table {{ border-collapse: collapse; width: 100%; }}
        th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
        th {{ background-color: #4CAF50; color: white; }}
        .passed {{ color: green; }}
        .failed {{ color: red; }}
        h1, h2, h3 {{ color: #333; }}
        code {{ background: #f4f4f4; padding: 2px 6px; border-radius: 3px; }}
    </style>
</head>
<body>
<pre style="white-space: pre-wrap;">{md}</pre>
</body>
</html>"""
        return html


class ReportGenerator:
    """
    Generates reports from stress test results.
    
    Usage:
        generator = ReportGenerator()
        report = generator.generate(suite_result)
        report_path = generator.save(report, "stress_report.md")
    """
    
    def __init__(self, output_dir: str = "stress_test_results"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def generate(self, suite_result: Dict) -> StressTestReport:
        """
        Generate report from test suite result.
        
        Args:
            suite_result: Dictionary from TestSuiteResult.to_dict()
            
        Returns:
            StressTestReport
        """
        # Build summary
        summary = {
            'total': suite_result.get('total_scenarios', 0),
            'passed': suite_result.get('passed_scenarios', 0),
            'failed': suite_result.get('failed_scenarios', 0),
            'pass_rate': suite_result.get('pass_rate', 0),
            'duration': suite_result.get('duration_seconds', 0),
            'all_passed': suite_result.get('all_passed', False),
        }
        
        # Build scenario list
        scenarios = []
        for s in suite_result.get('scenarios', []):
            scenarios.append({
                'name': s.get('scenario_name', 'Unknown'),
                'type': s.get('scenario_type', 'unknown'),
                'passed': s.get('passed', False),
                'duration': s.get('duration_seconds', 0),
                'halt_time_ms': s.get('halt_time_ms'),
                'max_drawdown': s.get('max_drawdown_pct', 0),
                'errors': s.get('errors', []),
            })
        
        # Generate recommendations
        recommendations = self._generate_recommendations(suite_result)
        
        return StressTestReport(
            title="Stress Test Report",
            generated_at=datetime.now(),
            summary=summary,
            scenarios=scenarios,
            recommendations=recommendations,
        )
    
    def _generate_recommendations(self, result: Dict) -> List[str]:
        """Generate recommendations based on results."""
        recs = []
        
        if not result.get('all_passed'):
            recs.append("⚠️ **CRITICAL**: Some stress tests failed. Do not deploy to production.")
        
        for s in result.get('scenarios', []):
            if not s.get('passed'):
                name = s.get('scenario_name', 'Unknown')
                errors = s.get('errors', [])
                
                if 'halt time' in ' '.join(errors).lower():
                    recs.append(f"Improve AMRC response time for {name} scenario")
                if 'drawdown' in ' '.join(errors).lower():
                    recs.append(f"Review risk limits for {name} scenario")
                if 'audit' in ' '.join(errors).lower():
                    recs.append("Investigate audit log integrity issues")
        
        if not recs:
            recs.append("✅ All tests passed. System is ready for production.")
            recs.append("Schedule next stress test in 24 hours.")
        
        return recs
    
    def save(
        self,
        report: StressTestReport,
        filename: Optional[str] = None,
        format: str = "md",
    ) -> Path:
        """
        Save report to file.
        
        Args:
            report: Report to save
            filename: Optional filename (auto-generated if None)
            format: 'md' or 'html'
            
        Returns:
            Path to saved file
        """
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"stress_report_{timestamp}.{format}"
        
        filepath = self.output_dir / filename
        
        if format == "html":
            content = report.to_html()
        else:
            content = report.to_markdown()
        
        with open(filepath, 'w') as f:
            f.write(content)
        
        logger.info(f"Report saved to {filepath}")
        return filepath
    
    def load_and_generate(self, json_path: str) -> StressTestReport:
        """Load results from JSON and generate report."""
        with open(json_path, 'r') as f:
            data = json.load(f)
        return self.generate(data)


# =============================================================================
# EXAMPLE USAGE
# =============================================================================

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    
    # Example result data
    example_result = {
        'start_time': '2024-12-06T10:00:00',
        'end_time': '2024-12-06T10:15:00',
        'duration_seconds': 900,
        'all_passed': True,
        'total_scenarios': 5,
        'passed_scenarios': 5,
        'failed_scenarios': 0,
        'pass_rate': 1.0,
        'scenarios': [
            {
                'scenario_name': 'Book Depth Collapse',
                'scenario_type': 'book_depth_collapse',
                'passed': True,
                'duration_seconds': 60,
                'halt_time_ms': 45.2,
                'max_drawdown_pct': 0.3,
                'errors': [],
            },
            {
                'scenario_name': 'Latency Spike',
                'scenario_type': 'latency_spike',
                'passed': True,
                'duration_seconds': 60,
                'halt_time_ms': 52.1,
                'max_drawdown_pct': 0.1,
                'errors': [],
            },
        ],
    }
    
    generator = ReportGenerator(output_dir=".test_reports")
    report = generator.generate(example_result)
    
    print("=== Markdown Report ===")
    print(report.to_markdown())
    
    # Save
    path = generator.save(report)
    print(f"\nSaved to: {path}")
